name: Vite Vue3 Vueuse Tailwind Css

permissions: read-all

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    # permissions:
    #   contents: write
    # permissions:
    #   contents: read
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # user_name: ${{ github.actor }}
          # user_email: lu199705@163.com
          # repo_name: ${{ github.repository }}
          # user_email: ${{ github.actor }}@users.noreply.github.com
          github_token: ${{ secrets.LZT_PAT }} # 此处修改为你的Secret名称
          # github_token: ${{ github.token }}
          publish_dir: ./dist
          full_commit_message: ${{ github.event.head_commit.message }}
